In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import ipywidgets as widgets
from ipywidgets import interact

In [2]:
df = pd.read_csv('phds_country.csv')
df.head()

,Country,Region,All Fields - Female,All Fields - Male,All S&E - Female,All S&E - Male,Physical & Biological Sciences - Female,Physical & Biological Sciences - Male,Mathematics & Computer Sciences - Female,Mathematics & Computer Sciences - Male,Agricultural Sciences - Female,Agricultural Sciences - Male,Social & Behavioral Sciences - Female,Social & Behavioral Sciences - Male,Engineering - Female,Engineering - Male,Non-S&E - Female,Non-S&E - Male
0,Algeria,Africa,3649,4310,1771,2337,673,458,243,382,89,93,378,575,388,829,1878,1973
1,Argentina (2009),America,515,422,371,291,224,142,29,45,10,8,75,61,33,35,144,131
2,Armenia,Asia,221,393,44,166,25,86,0,0,6,3,7,24,6,53,177,227
3,Australia,Oceania,2911,2914,1362,1769,563,663,79,193,90,85,448,231,182,597,1549,1145
4,Austria,Europe,1064,1436,473,828,173,229,38,152,9,20,129,90,124,337,591,608

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 18 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Country                                   56 non-null     object
 1   Region                                    56 non-null     object
 2   All Fields - Female                       56 non-null     int64
 3   All Fields - Male                         56 non-null     int64
 4   All S&E - Female                          56 non-null     int64
 5   All S&E - Male                            56 non-null     int64
 6   Physical & Biological Sciences - Female   56 non-null     int64
 7   Physical & Biological Sciences - Male     56 non-null     int64
 8   Mathematics & Computer Sciences - Female  56 non-null     int64
 9   Mathematics & Computer Sciences - Male    56 non-null     int64
 10  Agricultural Sciences - Female            56 non-null     int64
 11  Agricultural Sciences - Male              56 non-null     int64
 12  Social & Behavioral Sciences - Female     56 non-null     int64
 13  Social & Behavioral Sciences - Male       56 non-null     int64
 14  Engineering - Female                      56 non-null     int64
 15  Engineering - Male                        56 non-null     int64
 16  Non-S&E - Female                          56 non-null     int64
 17  Non-S&E - Male                            56 non-null     int64
dtypes: int64(16), object(2)
memory usage: 8.0+ KB

In [4]:
df['All Fields - Female %'] = (df['All Fields - Female']/(df['All Fields - Female'] + df['All Fields - Male']))*100
df['All Fields - Male %'] = (df['All Fields - Male']/(df['All Fields - Female'] + df['All Fields - Male']))*100
df['All Fields - Female %'] = round(df['All Fields - Female %'])
df['All Fields - Male %'] = round(df['All Fields - Male %'])

df['Non-S&E - Female %'] = (df['Non-S&E - Female']/(df['Non-S&E - Female'] + df['Non-S&E - Male']))*100
df['Non-S&E - Male %'] = (df['Non-S&E - Male']/(df['Non-S&E - Female'] + df['Non-S&E - Male']))*100
df['Non-S&E - Female %'] = round(df['Non-S&E - Female %'])
df['Non-S&E - Male %'] = round(df['Non-S&E - Male %'])

df['All S&E - Female %'] = (df['All S&E - Female']/(df['All S&E - Female'] + df['All S&E - Male']))*100
df['All S&E - Male %'] = (df['All S&E - Male']/(df['All S&E - Female'] + df['All S&E - Male']))*100
df['All S&E - Female %'] = round(df['All S&E - Female %'])
df['All S&E - Male %'] = round(df['All S&E - Male %'])

df['Agricultural Sciences - Female %'] = (df['Agricultural Sciences - Female']/(df['Agricultural Sciences - Female'] + df['Agricultural Sciences - Male']))*100
df['Agricultural Sciences - Male %'] = (df['Agricultural Sciences - Male']/(df['Agricultural Sciences - Female'] + df['Agricultural Sciences - Male']))*100
df['Agricultural Sciences - Female %'] = round(df['Agricultural Sciences - Female %'])
df['Agricultural Sciences - Male %'] = round(df['Agricultural Sciences - Male %'])

df['Engineering - Female %'] = (df['Engineering - Female']/(df['Engineering - Female'] + df['Engineering - Male']))*100
df['Engineering - Male %'] = (df['Engineering - Male']/(df['Engineering - Female'] + df['Engineering - Male']))*100
df['Engineering - Female %'] = round(df['Engineering - Female %'])
df['Engineering - Male %'] = round(df['Engineering - Male %'])

df['Mathematics & Computer Sciences - Female %'] = (df['Mathematics & Computer Sciences - Female']/(df['Mathematics & Computer Sciences - Female'] + df['Mathematics & Computer Sciences - Male']))*100
df['Mathematics & Computer Sciences - Male %'] = (df['Mathematics & Computer Sciences - Male']/(df['Mathematics & Computer Sciences - Female'] + df['Mathematics & Computer Sciences - Male']))*100
df['Mathematics & Computer Sciences - Female %'] = round(df['Mathematics & Computer Sciences - Female %'])
df['Mathematics & Computer Sciences - Male %'] = round(df['Mathematics & Computer Sciences - Male %'])

df['Physical & Biological Sciences - Female %'] = (df['Physical & Biological Sciences - Female']/(df['Physical & Biological Sciences - Female'] + df['Physical & Biological Sciences - Male']))*100
df['Physical & Biological Sciences - Male %'] = (df['Physical & Biological Sciences - Male']/(df['Physical & Biological Sciences - Female'] + df['Physical & Biological Sciences - Male']))*100
df['Physical & Biological Sciences - Female %'] = round(df['Physical & Biological Sciences - Female %'])
df['Physical & Biological Sciences - Male %'] = round(df['Physical & Biological Sciences - Male %'])

df['Social & Behavioral Sciences - Female %'] = (df['Social & Behavioral Sciences - Female']/(df['Social & Behavioral Sciences - Female'] + df['Social & Behavioral Sciences - Male']))*100
df['Social & Behavioral Sciences - Male %'] = (df['Social & Behavioral Sciences - Male']/(df['Social & Behavioral Sciences - Female'] + df['Social & Behavioral Sciences - Male']))*100
df['Social & Behavioral Sciences - Female %'] = round(df['Social & Behavioral Sciences - Female %'])
df['Social & Behavioral Sciences - Male %'] = round(df['Social & Behavioral Sciences - Male %'])

In [5]:
df.head()

,Country,Region,All Fields - Female,All Fields - Male,All S&E - Female,All S&E - Male,Physical & Biological Sciences - Female,Physical & Biological Sciences - Male,Mathematics & Computer Sciences - Female,Mathematics & Computer Sciences - Male,...,Agricultural Sciences - Female %,Agricultural Sciences - Male %,Engineering - Female %,Engineering - Male %,Mathematics & Computer Sciences - Female %,Mathematics & Computer Sciences - Male %,Physical & Biological Sciences - Female %,Physical & Biological Sciences - Male %,Social & Behavioral Sciences - Female %,Social & Behavioral Sciences - Male %
0,Algeria,Africa,3649,4310,1771,2337,673,458,243,382,...,49.0,51.0,32.0,68.0,39.0,61.0,60.0,40.0,40.0,60.0
1,Argentina (2009),America,515,422,371,291,224,142,29,45,...,56.0,44.0,49.0,51.0,39.0,61.0,61.0,39.0,55.0,45.0
2,Armenia,Asia,221,393,44,166,25,86,0,0,...,67.0,33.0,10.0,90.0,NaN,NaN,23.0,77.0,23.0,77.0
3,Australia,Oceania,2911,2914,1362,1769,563,663,79,193,...,51.0,49.0,23.0,77.0,29.0,71.0,46.0,54.0,66.0,34.0
4,Austria,Europe,1064,1436,473,828,173,229,38,152,...,31.0,69.0,27.0,73.0,20.0,80.0,43.0,57.0,59.0,41.0

In [6]:
menu_options = ['All Ph.D.s', 'Non-Science Ph.D.s', 
                'All Science & Engineering', 'Agricultural', 
                'Engineering', 'Math & Computer Science', 
                'Physical & Biological', 'Social & Behavioral']

order_by = ['Ascending % of Females', 'Region']

def interactive_plot(menu_selection, female, male, all_phd, order):
    
    rows_df = []
    
    fig, ax = plt.subplots(figsize=(10,6))

    plt.xticks(rotation = 90)
    
    if(order == 'Ascending % of Females'):
    
        if(menu_selection == 'All Ph.D.s'):

            rows_df = ['All Fields - Female %', 'All Fields - Male %']

            df_plot = df.sort_values(by = 'All Fields - Female %', ascending = True)

            if((female == True) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'All Fields - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)
                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'All Fields - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            elif((female == True) & (male == False)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'All Fields - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)


            elif((female == False) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'All Fields - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            else:

                return

        elif(menu_selection == 'Non-Science Ph.D.s'):

            rows_df = ['Non-S&E - Female %', 'Non-S&E - Male %']

            df_plot = df.sort_values(by = 'Non-S&E - Female %', ascending = True)

            if((female == True) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Non-S&E - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)
                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Non-S&E - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            elif((female == True) & (male == False)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Non-S&E - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)


            elif((female == False) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Non-S&E - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            else:

                return

        elif(menu_selection == 'All Science & Engineering'):

            rows_df = ['All S&E - Female %', 'All S&E - Male %']

            df_plot = df.sort_values(by = 'All S&E - Female %', ascending = True)

            if((female == True) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'All S&E - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)
                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'All S&E - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            elif((female == True) & (male == False)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'All S&E - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)


            elif((female == False) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'All S&E - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            else:

                return

        elif(menu_selection == 'Agricultural'):

            rows_df = ['Agricultural Sciences - Female %', 'Agricultural Sciences - Male %']

            df_plot = df.sort_values(by = 'Agricultural Sciences - Female %', ascending = True)

            if((female == True) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Agricultural Sciences - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)
                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Agricultural Sciences - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            elif((female == True) & (male == False)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Agricultural Sciences - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)


            elif((female == False) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Agricultural Sciences - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            else:

                return

        elif(menu_selection == 'Engineering'):

            rows_df = ['Engineering - Female %', 'Engineering - Male %']

            df_plot = df.sort_values(by = 'Engineering - Female %', ascending = True)

            if((female == True) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Engineering - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)
                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Engineering - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            elif((female == True) & (male == False)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Engineering - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)


            elif((female == False) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Engineering - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            else:

                return

        elif(menu_selection == 'Math & Computer Science'):

            rows_df = ['Mathematics & Computer Sciences - Female %', 'Mathematics & Computer Sciences - Male %']

            df_plot = df.sort_values(by = 'Mathematics & Computer Sciences - Female %', ascending = True)

            if((female == True) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Mathematics & Computer Sciences - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)
                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Mathematics & Computer Sciences - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            elif((female == True) & (male == False)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Mathematics & Computer Sciences - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)


            elif((female == False) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Mathematics & Computer Sciences - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            else:

                return

        elif(menu_selection == 'Physical & Biological'):

            rows_df = ['Physical & Biological Sciences - Female %', 'Physical & Biological Sciences - Male %']

            df_plot = df.sort_values(by = 'Physical & Biological Sciences - Female %', ascending = True)

            if((female == True) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Physical & Biological Sciences - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)
                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Physical & Biological Sciences - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            elif((female == True) & (male == False)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Physical & Biological Sciences - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)


            elif((female == False) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Physical & Biological Sciences - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            else:

                return

        elif(menu_selection == 'Social & Behavioral'):

            rows_df = ['Social & Behavioral Sciences - Female %', 'Social & Behavioral Sciences - Male %']

            df_plot = df.sort_values(by = 'Social & Behavioral Sciences - Female %', ascending = True)

            if((female == True) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Social & Behavioral Sciences - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)
                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Social & Behavioral Sciences - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            elif((female == True) & (male == False)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Social & Behavioral Sciences - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)


            elif((female == False) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Social & Behavioral Sciences - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            else:

                return
            
    if(order == 'Region'):
    
        if(menu_selection == 'All Ph.D.s'):

            rows_df = ['All Fields - Female %', 'All Fields - Male %']

            df_plot = df.sort_values(by = ['Region', 'All Fields - Female %'], ascending = [True, True])

            if((female == True) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'All Fields - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)
                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'All Fields - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            elif((female == True) & (male == False)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'All Fields - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)


            elif((female == False) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'All Fields - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            else:

                return

        elif(menu_selection == 'Non-Science Ph.D.s'):

            rows_df = ['Non-S&E - Female %', 'Non-S&E - Male %']

            df_plot = df.sort_values(by = ['Region', 'Non-S&E - Female %'], ascending = [True, True])

            if((female == True) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Non-S&E - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)
                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Non-S&E - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            elif((female == True) & (male == False)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Non-S&E - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)


            elif((female == False) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Non-S&E - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            else:

                return

        elif(menu_selection == 'All Science & Engineering'):

            rows_df = ['All S&E - Female %', 'All S&E - Male %']

            df_plot = df.sort_values(by = ['Region', 'All S&E - Female %'], ascending = [True, True])

            if((female == True) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'All S&E - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)
                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'All S&E - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            elif((female == True) & (male == False)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'All S&E - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)


            elif((female == False) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'All S&E - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            else:

                return

        elif(menu_selection == 'Agricultural'):

            rows_df = ['Agricultural Sciences - Female %', 'Agricultural Sciences - Male %']

            df_plot = df.sort_values(by = ['Region', 'Agricultural Sciences - Female %'], ascending = [True, True])

            if((female == True) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Agricultural Sciences - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)
                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Agricultural Sciences - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            elif((female == True) & (male == False)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Agricultural Sciences - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)


            elif((female == False) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Agricultural Sciences - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            else:

                return

        elif(menu_selection == 'Engineering'):

            rows_df = ['Engineering - Female %', 'Engineering - Male %']

            df_plot = df.sort_values(by = ['Region', 'Engineering - Female %'], ascending = [True, True])

            if((female == True) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Engineering - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)
                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Engineering - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            elif((female == True) & (male == False)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Engineering - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)


            elif((female == False) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Engineering - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            else:

                return

        elif(menu_selection == 'Math & Computer Science'):

            rows_df = ['Mathematics & Computer Sciences - Female %', 'Mathematics & Computer Sciences - Male %']

            df_plot = df.sort_values(by = ['Region', 'Mathematics & Computer Sciences - Female %'], ascending = [True, True])

            if((female == True) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Mathematics & Computer Sciences - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)
                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Mathematics & Computer Sciences - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            elif((female == True) & (male == False)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Mathematics & Computer Sciences - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)


            elif((female == False) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Mathematics & Computer Sciences - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            else:

                return

        elif(menu_selection == 'Physical & Biological'):

            rows_df = ['Physical & Biological Sciences - Female %', 'Physical & Biological Sciences - Male %']

            df_plot = df.sort_values(by = ['Region', 'Physical & Biological Sciences - Female %'], ascending = [True, True])

            if((female == True) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Physical & Biological Sciences - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)
                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Physical & Biological Sciences - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            elif((female == True) & (male == False)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Physical & Biological Sciences - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)


            elif((female == False) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Physical & Biological Sciences - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            else:

                return

        elif(menu_selection == 'Social & Behavioral'):

            rows_df = ['Social & Behavioral Sciences - Female %', 'Social & Behavioral Sciences - Male %']

            df_plot = df.sort_values(by = ['Region', 'Social & Behavioral Sciences - Female %'], ascending = [True, True])

            if((female == True) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Social & Behavioral Sciences - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)
                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Social & Behavioral Sciences - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            elif((female == True) & (male == False)):

                ax = sns.scatterplot(x='Country', y= rows_df[0], size = 'Social & Behavioral Sciences - Female', sizes = (0,500), data=df_plot, color = '#00CED1', ax=ax)


            elif((female == False) & (male == True)):

                ax = sns.scatterplot(x='Country', y= rows_df[1], size = 'Social & Behavioral Sciences - Male', sizes = (0,500), data=df_plot, color = '#FF8C00', ax=ax)

            else:

                return
        
    plt.ylim(0,100)
    ax.set_ylabel('PERCENT OF TOTAL')
    ax.set_xlabel('PHD-GRANTING COUNTRY')
    plt.title("Global Ph.D.s Gender Gap (2010)")
    ax.get_legend().remove()

interact(interactive_plot, 
         menu_selection = widgets.Dropdown(options= menu_options, description='View Type:'),
         female = widgets.Checkbox(value = True, description = 'Female'),
         male = widgets.Checkbox(value = True, description = 'Male'),
         all_phd = widgets.Checkbox(value = False, description = 'All Ph.D.s'),
         order = widgets.ToggleButtons(options = order_by))

interactive(children=(Dropdown(description='View Type:', options=('All Ph.D.s', 'Non-Science Ph.D.s', 'All Sci…